// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt5ReB8xYv9HKsA1htm7KsHsqs9DGtcuM',
    appId: '1:521026637434:web:13fffbd4773860f654f5c3',
    messagingSenderId: '521026637434',
    projectId: 'brigade-rouge',
    authDomain: 'brigade-rouge.firebaseapp.com',
    storageBucket: 'brigade-rouge.firebasestorage.app',
    measurementId: 'G-TJLXPYSKRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbQuPPI7wnr1oif5RslClmTlC7P5c9wo',
    appId: '1:521026637434:android:977c3088cf524b0954f5c3',
    messagingSenderId: '521026637434',
    projectId: 'brigade-rouge',
    storageBucket: 'brigade-rouge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNUqHFSxyC1OiTm155PKz7O0NDhbuxtW4',
    appId: '1:521026637434:ios:0bbe408aa2c2b46d54f5c3',
    messagingSenderId: '521026637434',
    projectId: 'brigade-rouge',
    storageBucket: 'brigade-rouge.firebasestorage.app',
    iosBundleId: 'com.br01.brigadeRouge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt5ReB8xYv9HKsA1htm7KsHsqs9DGtcuM',
    appId: '1:521026637434:web:64b06585d965abc854f5c3',
    messagingSenderId: '521026637434',
    projectId: 'brigade-rouge',
    authDomain: 'brigade-rouge.firebaseapp.com',
    storageBucket: 'brigade-rouge.firebasestorage.app',
    measurementId: 'G-9PG7B251DV',
  );
}
